export const pathologiesMinimalList = [
  'Perturbações ansiosos e/ou de humor',
  'Alterações sensoperceptivas',
  'Avaliações para concursos',
  'Conflitos laborais e dificuldades na adaptação à vida profissional',
  'Conflitos familiares',
  'Problemas de relacionamento',
  'Stress',
  'Lutos',
  'Fobias e outros sintomas psiquiátricos',
  'Problemas de memória',
  'Dificuldades no sono',
  'Perder peso'
]

export const pathologiesList = [
  'Perturbações ansiosos e/ou de humor',
  'Alterações sensoperceptivas',
  'Avaliações para concursos',
  'Conflitos laborais e dificuldades na adaptação à vida profissional',
  'Conflitos familiares',
  'Problemas de relacionamento',
  'Stress',
  'Lutos',
  'Fobias e outros sintomas psiquiátricos',
  'Problemas de memória',
  'Dificuldades no sono',
  'Perder peso',
  'Insegurança, baixa auto estima, timidez excessiva',
  'Problemas de identidade e/ou orientação sexual',
  'Problemas do comportamento e/ou agressividade',
  'Perturbações psicossomáticas diversas',
  'Dificuldade na integração em grupos sociais',
  'Dificuldades na intimidade/sexualidade',
  'Avaliações para concursos',
  'Conflitos laborais e dificuldades na adaptação à vida profissional',
  'Conflitos familiares',
  'Problemas de relacionamento',
  'Stress',
  'Lutos'
]
